version: "3"

services:
  broker:
    image: docker.io/rabbitmq:3.12.6-management
    hostname: broker
    environment:
      - TZ=Europe/Paris
    ports:
      - 1883:1883
      - 5672:5672
      - 15672:15672
    volumes:
      - ./broker/config/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
      - ./broker/config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./broker/config/conf.d:/etc/rabbitmq/conf.d/      
      - ./broker/config/definitions.json:/etc/rabbitmq/definitions.json:ro
      - broker-data:/var/lib/rabbitmq/
      - broker-logs:/var/log/rabbitmq/

volumes:
  broker-data:
  broker-logs:
